version: "3.8"

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - memcache
    # Mount the host ./app directory into /app/app in the container so
    # the Python import `import app` resolves to /app/app (package dir).
    volumes:
      - ./app:/app/app

  memcache:
    image: memcached:latest
    container_name: memcache
    ports:
      - "11211:11211"
